using System;
using HlumisaProperties.Domain.Entities;

namespace HlumisaProperties.Api
{
    /// <summary>
    /// Seed data for the transaction ledger (Books).
    /// Populated only when the TransactionLedgers table is empty.
    /// </summary>
    public static class TransactionLedgerSeedData
    {
        public static TransactionLedger[] Rows { get; } = new[]
        {
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "MASOKA",
                Seller = "E/L MANCATA",
                OriginalAmount = 0m,
                DueToSeller = 140000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "1588",
                Area = "WELLS ESTATE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "SWELINDAWO",
                Seller = "SMILO",
                OriginalAmount = 0m,
                DueToSeller = 150000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 15000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "KITSANA",
                Seller = "NKABI",
                OriginalAmount = 0m,
                DueToSeller = 110000m,
                Deposit = 60000m,
                LostDeed = 50000m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "21755",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "NONJAKAZI",
                Seller = "SAM",
                OriginalAmount = 0m,
                DueToSeller = 195000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 15000m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "65696",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "NDABAMBI",
                Seller = "E/L JOHNSON",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 21000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "18741",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "MINI",
                Seller = "MTATI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 15000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "31834",
                Area = "KAMVELIHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "PLAATJIES",
                Seller = "E/L BINDA",
                OriginalAmount = 0m,
                DueToSeller = 160000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13500m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "27922",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "GWATUDZI",
                Seller = "SMILE",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 21500m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "TOBI",
                Seller = "MZOZOYANA",
                OriginalAmount = 0m,
                DueToSeller = 205600m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 15600m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 90000m,
                ErfNumber = "28514",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "HEWANA",
                Seller = "E/L MBUTUMA",
                OriginalAmount = 0m,
                DueToSeller = 24000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 11000m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "20342",
                Area = "BETHELSDORP",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "MZAYIDUME",
                Seller = "E/L MCOTOYI",
                OriginalAmount = 0m,
                DueToSeller = 140000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 25000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "16429",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "GONI",
                Seller = "FANS",
                OriginalAmount = 0m,
                DueToSeller = 13000m,
                Deposit = 7000m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "7958",
                Area = "BOOYSENS",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "NQWENISO",
                Seller = "DAVIDS",
                OriginalAmount = 0m,
                DueToSeller = 163000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 30000m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 40000m,
                ErfNumber = "27114",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "JOHNSON",
                Seller = "JONAS",
                OriginalAmount = 0m,
                DueToSeller = 180000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "30583",
                Area = "MISSIONVALLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "GABAYI",
                Seller = "E/L GANA",
                OriginalAmount = 0m,
                DueToSeller = 190000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "KWATSHA",
                Seller = "MZOZOYANA",
                OriginalAmount = 0m,
                DueToSeller = 170000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 50000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 100000m,
                ErfNumber = "24014",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "BOKOYI",
                Seller = "MZOZOYANA",
                OriginalAmount = 0m,
                DueToSeller = 190000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 40000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 44500m,
                ErfNumber = "31553",
                Area = "KAMVELIHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "PONO/KAWE",
                Seller = "E/L CAKWE",
                OriginalAmount = 0m,
                DueToSeller = 170000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 24000m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "ZEPE",
                Seller = "MANELI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 40000m,
                TransferCosts = 0m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "BOND",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "SIDLABANE",
                Seller = "E/L SKOSANA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 28500m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "SIMANGO",
                Seller = "SIMANGO",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 21500m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "19007",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JANUARY",
                Buyer = "BEBE",
                Seller = "E/L QOLANI",
                OriginalAmount = 0m,
                DueToSeller = 203000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 14000m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "65033",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "KONA",
                Seller = "LUBAMBO",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "7941",
                Area = "DESPATCH",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "SAM",
                Seller = "DLAKUDLA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 14000m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "65696",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "MZOZOYANA",
                Seller = "NTEYI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 75000m,
                TransferCosts = 0m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "5351",
                Area = "WELLS ESTATE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "SIWENDU",
                Seller = "E/L MOSI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 10000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "22718",
                Area = "KAMVELIHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "MANELI",
                Seller = "RALA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 100000m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "27969",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "SIWENDU",
                Seller = "MNYAMANA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "32937",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "SIYA",
                Seller = "MAVATHA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 6000m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "27281",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "NCULA",
                Seller = "NOTSHOBA",
                OriginalAmount = 0m,
                DueToSeller = 160000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "30801",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "FEBRUARY",
                Buyer = "NTSHOKO",
                Seller = "E/L MPOZA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "32293",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "XHANTI",
                Seller = "SODZEME",
                OriginalAmount = 0m,
                DueToSeller = 280000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 70000m,
                TransferCosts = 20000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "3902",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "XHANTI",
                Seller = "LUKWE",
                OriginalAmount = 0m,
                DueToSeller = 200000m,
                Deposit = 0m,
                LostDeed = 38000m,
                Commission = 25000m,
                TransferCosts = 18000m,
                MasterFees = 38000m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 170000m,
                ErfNumber = "4077",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MPALALA",
                Seller = "MPI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "33931",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MCAKUMBANA",
                Seller = "FUBESI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "13067",
                Area = "BOOYSENS PARK",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "BILLY",
                Seller = "MAVATA",
                OriginalAmount = 0m,
                DueToSeller = 195000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 25000m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 120000m,
                ErfNumber = "26739",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "TSILITE",
                Seller = "NYAMAKAZI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 21000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 40000m,
                ErfNumber = "14797",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MAFUXWANA",
                Seller = "NXADI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "16850",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MLUNGWANA",
                Seller = "KOTA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 14800m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "26420",
                Area = "BETHELSDORP",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MPOFU",
                Seller = "NALITI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 3, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MARCH",
                Buyer = "MZOZOYANA",
                Seller = "MJIJWA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 40000m,
                TransferCosts = 17000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 150000m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "MDABULA",
                Seller = "MDABULA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 25000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "2835",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "NYIKI",
                Seller = "KLAAS",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "12169",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "MKHONTO",
                Seller = "E/L YOKO",
                OriginalAmount = 0m,
                DueToSeller = 190000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 16000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 106950m,
                ErfNumber = "24755",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "VANTYI",
                Seller = "MAYISHE",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "9106",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "FANTA",
                Seller = "KHWALO",
                OriginalAmount = 0m,
                DueToSeller = 200000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 20000m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "MZALAZALA",
                Seller = "JOKANI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "16758",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "MZOZOYANA",
                Seller = "MAGABA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 5000m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "NTONTELA",
                Seller = "MATANJANA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 20000m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "BOND",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "MANELI",
                Seller = "MANJEZI",
                OriginalAmount = 0m,
                DueToSeller = 195000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 10000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 4, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "APRIL",
                Buyer = "NGANGANI",
                Seller = "NGANGANI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 10000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "FUZANI",
                Seller = "E/L TORO",
                OriginalAmount = 0m,
                DueToSeller = 39000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 16220m,
                ErfNumber = "25475",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "MNYAMANA",
                Seller = "E/L DESI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "28121",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "NTSINI",
                Seller = "E/L TUSWA",
                OriginalAmount = 0m,
                DueToSeller = 153000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 15000m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 80000m,
                ErfNumber = "27040",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "ZWENI",
                Seller = "E/L MAPU",
                OriginalAmount = 0m,
                DueToSeller = 60000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 34700m,
                ErfNumber = "11679",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "CHIEF SAI",
                Seller = "",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "25600",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "JELA",
                Seller = "SIGUTYWA",
                OriginalAmount = 0m,
                DueToSeller = 150000m,
                Deposit = 0m,
                LostDeed = 13000m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "34863",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "MZOZOYANA",
                Seller = "NTENTENI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 40000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "SNAM",
                Seller = "E/L SLATER",
                OriginalAmount = 0m,
                DueToSeller = 225000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 100000m,
                ErfNumber = "1357",
                Area = "WELLS ESTATE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "",
                Seller = "PALAMENTE",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "27366",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "MAY",
                Buyer = "MANGE",
                Seller = "E/L TALAMBA",
                OriginalAmount = 0m,
                DueToSeller = 119701m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 20000m,
                MasterFees = 10520m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 81381m,
                ErfNumber = "9708",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MTSHAULANA",
                Seller = "ZENZILE",
                OriginalAmount = 0m,
                DueToSeller = 83000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MJUZA",
                Seller = "MAYEKISO",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 72200m,
                ErfNumber = "17993",
                Area = "MISSIONVALE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MAFUNDA",
                Seller = "DAYIMANI",
                OriginalAmount = 0m,
                DueToSeller = 180000m,
                Deposit = 0m,
                LostDeed = 7800m,
                Commission = 0m,
                TransferCosts = 17000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 92200m,
                ErfNumber = "",
                Area = "WELLS ESTATE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "",
                Seller = "BOOI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MZOZOYANA",
                Seller = "NANGU",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 60000m,
                TransferCosts = 20000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "TSOTSO",
                Seller = "",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "",
                Seller = "THANDIWE",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MZOZOYANA",
                Seller = "E/L TSHIRA",
                OriginalAmount = 0m,
                DueToSeller = 250000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 50000m,
                TransferCosts = 20000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "",
                Seller = "NGXANGANI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 30000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "SIYA",
                Seller = "BAKWANA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "BLOEMENDAL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MANELI",
                Seller = "JONAS",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 20000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "",
                Seller = "KHASTA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 20000m,
                TransferCosts = 20000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "JACK",
                Seller = "T MAN",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "NKANDLA",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "JOSEPH",
                Seller = "MTATI",
                OriginalAmount = 0m,
                DueToSeller = 117000m,
                Deposit = 0m,
                LostDeed = 50000m,
                Commission = 0m,
                TransferCosts = 17000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 80000m,
                ErfNumber = "",
                Area = "BLOEMENDAL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 6, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JUNE",
                Buyer = "MOODLEY",
                Seller = "SAM",
                OriginalAmount = 0m,
                DueToSeller = 153000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "UITENHAGE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MZOZOYANA",
                Seller = "E/L NYODI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 40000m,
                TransferCosts = 18000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MAHLAKAHLAKA",
                Seller = "NZUBE",
                OriginalAmount = 0m,
                DueToSeller = 94000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 16000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MZOZOYANA",
                Seller = "MPI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 150000m,
                TransferCosts = 17000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "33931",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MZOZOYANA",
                Seller = "MTATI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 25000m,
                TransferCosts = 17000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MZOZOYANA",
                Seller = "MPI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "FRANCE",
                Seller = "MAKHULU",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 60000m,
                TransferCosts = 0m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "BOND",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "ENTITY",
                Seller = "SIMANGA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 12500m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 25405m,
                ErfNumber = "1743",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "LEVEL",
                Seller = "VENA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 6000m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 7000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "38155",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "PAYI",
                Seller = "",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "MATYUNU",
                Seller = "",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 13000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 30000m,
                ErfNumber = "",
                Area = "KWANOBUHLE",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "YOYO",
                Seller = "E/L MANKEYA",
                OriginalAmount = 0m,
                DueToSeller = 180000m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "KWADWESI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 7, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "JULY",
                Buyer = "CENENDA",
                Seller = "BOOI",
                OriginalAmount = 0m,
                DueToSeller = 147200m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 14000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 27200m,
                ErfNumber = "",
                Area = "IBHAYI",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "AUGUST",
                Buyer = "KWATSHUBE",
                Seller = "NGUMBELA",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 15000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "14848",
                Area = "BLOEMENDAL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "AUGUST",
                Buyer = "MZOZOYANA",
                Seller = "E/L THEMBANI",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 25000m,
                TransferCosts = 20000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "33259",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
            new TransactionLedger
            {
                Date = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc),
                Month = "AUGUST",
                Buyer = "MATI",
                Seller = "",
                OriginalAmount = 0m,
                DueToSeller = 0m,
                Deposit = 0m,
                LostDeed = 0m,
                Commission = 0m,
                TransferCosts = 20000m,
                MasterFees = 0m,
                ElecCert = 0m,
                WaterAccount = 0m,
                Section118 = 0m,
                Balance = 0m,
                ErfNumber = "",
                Area = "MOTHERWELL",
                Status = "Pending",
                CellColors = "{}",
            },
        };
    }
}
